[package]
name = "ghosttea-font-fixture-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
ghosttea-text = { path = "../ghosttea-text", features = ["fixture"] }
serde_json.workspace = true
